---
- name: Ensure Apache is installed
  yum: name=httpd state=present

- name: Start Apache
  service: name=httpd state=started enabled=yes

- name: Deploy configuration file
  template: src=httpd.j2 dest=/etc/httpd/conf/httpd.conf
  notify:
  - Restart Apache

- name: Create directory for site files
  file: path={{ doc_root }} state=directory recurse=yes

- name: Copy site files
  template: src=index.j2 dest={{ doc_root }}/index.html
